### PR TITLE
Providing a baseline commit anticipating cleaner DI factoring

### PR DESCRIPTION
**Pull request by mwpowellhtx**
I tried to pare back the clean up, benign changes as much as possible as early as possible. The latter commits represent increasingly strategic updates, until the last commit that I believe puts PerfIt in a better position to start considering DI agnostic re-factoring.

The build passes locally; the unit tests all pass, but for one, the Task.Delay issue.

I'll be looking into a better factoring of the runtime and related concerns. Another one that popped up as a potentially repeating concern are the discovery models, which are basically the same but for minor framework differences.

Thanks and feel free to follow up with any questions.

MP

### CODE REVIEW

**Comment by mwpowellhtx** [comment]
After further review, I'm closing this PR, due to the fact that I shoe horned in a PerformanceCounterCategory in one of the counters. That's somewhat against the grain of the current design. However, I'm working on a category-centric design that would better fit. The tricky part is having some sort of access to the internal counter creation data collection after the category has been created. Will let you know how that goes.

**Comment by aliostad** [comment]
Sorry, big failure on my part not being able to review this. I apologise, it has been crazy.

**Comment by mwpowellhtx** [comment]
It's no problem. I've branched and run with a measurement diagnostics API that better suits my needs.

**Comment by mwpowellhtx** [comment]
Merry Christmas and early HNY.

It's been a bit of a rabbit hole for me, but I've finally got a presentable library that better suits my needs.

I'd like to [solicit your feedback](http://github.com/mwpowellhtx/MeasureIt/) if you're up for it. Some obvious things right off that bat; I target "simple" service oriented measurement, and Web API out of the gate. I may push towards MVC, eventually, but there is also the MVC Core re-factoring be considerate of in the near future, if not already.

The rabbit hole for me were contending with the the nuances of the counters, categories, etc, themselves. There were definitely a couple several items that needed to be grokked, so to speak, before being able to stitch it together in any sort of framework. Once I got the hang of it, though, pretty straightforward.

For installation, I decided to separate this concern from the library itself, but I do provide the installer discovery service, either as a dependency injection container warm up. It should work either way. Basically, I was inspired by your installation methods and decided to separate those concerns into discovery agents and services. Definitely, MeasureIt is Dependency Injection friendly, so it's not for everyone. It's possibly to instrument something apart from DI, but more than likely, some container is involved when an app warrants diagnostic measurement.

Haven't quite published things yet, but am poised to. The packaging is there, I just need to dot my I's and cross my T's and publish.

Thank so much!

**Comment by mwpowellhtx** [comment]
It took me longer than I'd wanted, but I think it's more or less [presentable](http://github.com/mwpowellhtx/MeasureIt/). Hopefully including packaging ducks in a row as well.

I wanted to provide Autofac container support for my own purposes. But since I was there and already dealing with Castle for interception purposes anyway, decided to also throw in Castle Windsor support.

I have one last thing to look into for ASP.NET MVC support and that's considering begin/end measurement boundaries. The options are roughed in, but for the moment only the Action is being measured.

Thanks for the inspiring library!

**Pull request closed without merging**
